plugins:
  - jekyll-seo-tag

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

description:
  A tutorial that shows JavaSE developers how to get started with OSGi.

sass:
    style: compressed  
